### ISSUE TITLE
Doc.rs fails to build project with jsonnet-sys in dependencies

### ISSUE THREAD

**Issue by darlaam** [anguslees/rust-jsonnet#9]
Seems that the build script try to write in src directory, which is not/no more permitted.
cf [this issue](https://github.com/rust-lang/docs.rs/issues/727)

Seems that you should use `$CARGO_OUT_DIR` to write.

**Comment by anguslees** [comment]
Thanks, will fix.

Do you know an easy way for me to verify my fix?  (before merging/publishing to docs.rs?)

**Comment by iilyak** [comment]
Hello I am trying to build https://github.com/ffizer/ffizer on nixos. In nixos builder doesn't have write access to source. I think the failure is caused by this issue. The output is quite cryptic (just for reference):
```
ffizer-deps> error: failed to run custom build command for `jsonnet-sys v0.6.0`
ffizer-deps> Caused by:
ffizer-deps> process didn't exit successfully: `/build/dummy-src/target/release/build/jsonnet-sys-948082e4a0558fbf/build-script-build` (exit code: 101)
ffizer-deps> --- stdout
ffizer-deps> embedding: "jsonnet/stdlib/std.jsonnet" -> "jsonnet/core/std.jsonnet.h"
ffizer-deps> --- stderr
ffizer-deps> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', /sources/jsonnet-sys-0.6.0/build.rs:28:47
ffizer-deps> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
ffizer-deps> warning: build failed, waiting for other jobs to finish...
ffizer-deps> error: build failed
ffizer-deps> [naersk] cargo returned with exit code 101, exiting
```

Would you be able to create a new release and push it to crates.io which includes https://github.com/anguslees/rust-jsonnet/pull/16 fix?

**Comment by rben01** [comment]
I am also seeing this issue. docs.rs can't build my crate because it has this crate as a dependency; I get the same `embedding: "jsonnet/stdlib/std.jsonnet" -> "jsonnet/core/std.jsonnet.h"` error.

**Comment by rben01** [comment]
On second thought it may be the `git submodule update` command running inside `build.rs` that's causing docs.rs to fail the build — docs.rs does not allow network connections. It may be fixable by wrapping everything in `main()` inside `if std::env::var("DOCS_RS").is_err() {...}`.
